### ISSUE TITLE
Settings #1

### ISSUE THREAD

**Issue by choiwook940** [choiwook940/starbucks-cloning#1]
# Description
Settings to begin.

## Task 
- [x] Style reset & favicon
- [x] Open graph & Twitter card
- [x] Google fonts
- [x] Google Material Icons
