### ISSUE TITLE
Header and dropdown menu #2

### ISSUE THREAD

**Issue by choiwook940** [choiwook940/starbucks-cloning#2]
# Description
Create header which contains logo, sub menu, main menu, dropdown menu, and badges.

# Task 
- [x] Create header and logo
- [x] Add sub menu
- [x] Add main menu and dropdown menu
- [x] Add badges
