### ISSUE TITLE
Element Slide #4

### ISSUE THREAD

**Issue by choiwook940** [choiwook940/starbucks-cloning#4]
# Description
Create notice section and make some slide effects.

## Task
- [x] Create notice section and add swiper to notification.
- [x] Create promotion slide and add slide effects.
- [x] Add slide toggle on promotion button.
