### ISSUE TITLE
Rewards and video section #5

### ISSUE THREAD

**Issue by choiwook940** [choiwook940/starbucks-cloning#5]
# Description
Create rewards and video section.

## Task
- [x] Create reward section and sign-in button.
- [x] Create Youtube iframe API.
- [x] Create repeated animation effects.
