### ISSUE TITLE
Fixed background-image and some animations #6

### ISSUE THREAD

**Issue by choiwook940** [choiwook940/starbucks-cloning#6]
# Description
Create several product and store section.

## Task
- [x] Create several section and add fixed background-images
- [x] Create 3D animation on a medal
- [x] Create scroll-based animation
